extends: .github

queue_rules:
  - name: default
    allow_inplace_checks: true
    conditions:
      - and: &CheckRuns
          - check-success=test
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]
  - name: lowprio
    queue_conditions:
      - and: *CheckRuns
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
    merge_conditions:
      - and: *CheckRuns
      - schedule=Mon-Fri 09:00-17:00[Europe/Paris]
    allow_inplace_checks: true
    batch_size: 7
    batch_max_wait_time: 5min
    queue_branch_merge_method: fast-forward
    disallow_checks_interruption_from_queues:
      - default
    merge_method: merge

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - and: *CheckRuns
      - check-success=semantic-pull-request
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - label!=manual merge
    actions:
      queue:
        name: default

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -merged
      - -closed
      - and: *CheckRuns
      - "check-success=Rule: changelog requirements (post_check)"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

merge_queue:
  max_parallel_checks: 5
